### ISSUE TITLE
Ball model should have more details

### ISSUE THREAD

**Issue by Calinou** [KOBUGE-Games/multiball#1]
The lack of detail of the ball model is clearly visible, especially on a large screen (1920×1080). [Neverball](http://neverball.org/) does it well; even at that resolution, you can't see the ball's triangles.

**Comment by bojidar-bg** [comment]
I think that if I use a UV Sphere instead of Icosphere it will be better...

**Comment by Calinou** [comment]
It can be any of them, as long as it's detailed enough.

**Comment by bojidar-bg** [comment]
Should be closed by 251cbef72927919519094411bd399b5c3c48d0b9 (which also made it LOD-ed)
