### ISSUE TITLE
Ball should cast shadows

### ISSUE THREAD

**Issue by Calinou** [KOBUGE-Games/multiball#2]
I don't know why (I've looked in editor), but the ball doesn't cast any shadows. It probably should.

**Comment by bojidar-bg** [comment]
@Calinou The ball doesn't cast shadows, because it is semi-transparent. I'm planning to remove shadows for some time, so that will not be a problem :smile:

**Comment by Calinou** [comment]
Well, in real life, semi-transparent objects do cast some sort of shadow.

**Comment by bojidar-bg** [comment]
Well, in godot they don't
