### ISSUE TITLE
Choose levels

### ISSUE THREAD

**Issue by ObaniGemini** [KOBUGE-Games/multiball#4]
Actually if you want to test another level, you have to make your level be named _level-ng-test.tscn_

We need a proper way to choose levels :
- **1** : enter the name/path of the level
- **2** : switching between levels with different buttons
- **3** switching between levels with a list
  - _hardcoded_ : All the levels names are entered in some file (like in [Minilens](https://github.com/KOBUGE-Games/minilens/blob/master/levels/packs.txt))
  - _proper_ : check files beginning with "level" in location `game/levels` and list them one after the other

**Comment by bojidar-bg** [comment]
That's partly incorrect, you can just delete+reinstance the level node in main.tscn... But, yeah, I agree that we need a list :smile:

**Comment by ObaniGemini** [comment]
Tell that to @jmf then for he stops crying :smile_cat:

**Comment by bojidar-bg** [comment]
Uh, right, fixed by d58e83b9914e84bdce0d5399ea253774f4c9eae0 :smile:

**Comment by bojidar-bg** [comment]
Uh, right, fixed by d58e83b9914e84bdce0d5399ea253774f4c9eae0 :smile:
